export const SAVE_TOKEN = 'SAVE_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';
export const SET_AUTH_FACEBOOK = 'SET_AUTH_FACEBOOK'
export const SET_AUTH_GOOGLE = 'SET_AUTH_GOOGLE'
export const SET_AUTH_EMAIL = 'SET_AUTH_EMAIL'